comment "Remove existing items";
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

comment "Add containers";
this forceAddUniform "CFB_TW_Rolled_Uniform";
for "_i" from 1 to 10 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 4 do {this addItemToUniform "ACE_morphine";};
this addItemToUniform "ACE_epinephrine";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_DefusalKit";
this addItemToUniform "ACE_Clacker";
this addItemToUniform "ACE_IR_Strobe_Item";
this addVest "V_PlateCarrierIAGL_oli";
for "_i" from 1 to 9 do {this addItemToVest "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addItemToVest "SmokeShellGreen";
this addBackpack "CFB_TW_Backpack_Kitbag";
this addItemToBackpack "ACE_wirecutter";
this addItemToBackpack "MineDetector";
this addItemToBackpack "SatchelCharge_Remote_Mag";
for "_i" from 1 to 3 do {this addItemToBackpack "DemoCharge_Remote_Mag";};
this addItemToBackpack "ClaymoreDirectionalMine_Remote_Mag";
this addHeadgear "CFB_TW_Helmet";
this addGoggles "rhs_googles_orange";

comment "Add weapons";
this addWeapon "rhs_weap_m4a1_carryhandle_grip";
this addPrimaryWeaponItem "rhsusf_acc_anpeq15A";
this addPrimaryWeaponItem "rhsusf_acc_ACOG";

comment "Add items";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "tf_anprc152_1";
this linkItem "NVGoggles_INDEP";
