comment "Remove existing items";
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

comment "Add containers";
this forceAddUniform "CFB_TW_Tshirt_Uniform";
for "_i" from 1 to 10 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToUniform "ACE_morphine";};
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_epinephrine";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_EarPlugs";};
this addVest "CFB_TW_Vest_PlateCarrier2";
for "_i" from 1 to 4 do {this addItemToVest "SmokeShell";};
for "_i" from 1 to 4 do {this addItemToVest "SmokeShellGreen";};
for "_i" from 1 to 11 do {this addItemToVest "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
for "_i" from 1 to 4 do {this addItemToVest "SmokeShellBlue";};
this addBackpack "CFB_TW_Backpack_Assault";
for "_i" from 1 to 40 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 25 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 25 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 14 do {this addItemToBackpack "ACE_bloodIV_500";};
this addHeadgear "CFB_TW_Helmet";

comment "Add weapons";
this addWeapon "rhs_weap_m4a1_carryhandle";
this addPrimaryWeaponItem "rhsusf_acc_anpeq15A";
this addPrimaryWeaponItem "rhsusf_acc_ACOG";

comment "Add items";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "tf_anprc152_1";
this linkItem "NVGoggles_INDEP";
[this,"CFB_Medic"] call bis_fnc_setUnitInsignia;
