comment "Remove existing items";
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;

comment "Add containers";
player forceAddUniform "rhs_uniform_emr_patchless";
for "_i" from 1 to 10 do {player addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
player addItemToUniform "ACE_epinephrine";
for "_i" from 1 to 2 do {player addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {player addItemToUniform "SmokeShellGreen";};
player addVest "rhs_6b23_digi_6sh92_vog_headset";
player addItemToVest "ACE_EarPlugs";
player addItemToVest "rhs_mag_rgd5";
for "_i" from 1 to 10 do {player addItemToVest "rhs_30Rnd_545x39_AK_green";};
player addBackpack "tf_mr3000_rhs";
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_EarPlugs";};
player addItemToBackpack "ACE_MapTools";
for "_i" from 1 to 6 do {player addItemToBackpack "rhs_VOG25";};
for "_i" from 1 to 5 do {player addItemToBackpack "rhs_VG40OP_white";};
for "_i" from 1 to 4 do {player addItemToBackpack "rhs_VG40OP_green";};
for "_i" from 1 to 4 do {player addItemToBackpack "rhs_VG40OP_red";};
player addItemToBackpack "Laserbatteries";
player addHeadgear "rhs_6b27m_digi";

comment "Add weapons";
player addWeapon "rhs_weap_ak74m_gp25";
player addPrimaryWeaponItem "rhs_acc_dtk";
player addWeapon "Laserdesignator_03";

comment "Add items";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "tf_fadak_3";
player linkItem "ItemGPS";
player linkItem "NVGoggles_INDEP";
