comment "Remove existing items";
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

comment "Add containers";
this forceAddUniform "rhs_uniform_emr_patchless";
for "_i" from 1 to 10 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 5 do {this addItemToUniform "ACE_morphine";};
this addItemToUniform "ACE_epinephrine";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShellGreen";};
this addVest "rhs_6b23_digi_6sh92_vog_headset";
this addItemToVest "ACE_EarPlugs";
this addItemToVest "rhs_mag_rgd5";
for "_i" from 1 to 10 do {this addItemToVest "rhs_30Rnd_545x39_AK_green";};
this addBackpack "tf_mr3000_rhs";
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_EarPlugs";};
this addItemToBackpack "ACE_MapTools";
for "_i" from 1 to 6 do {this addItemToBackpack "rhs_VOG25";};
for "_i" from 1 to 5 do {this addItemToBackpack "rhs_VG40OP_white";};
for "_i" from 1 to 4 do {this addItemToBackpack "rhs_VG40OP_green";};
for "_i" from 1 to 4 do {this addItemToBackpack "rhs_VG40OP_red";};
this addItemToBackpack "Laserbatteries";
this addHeadgear "rhs_6b27m_digi";

comment "Add weapons";
this addWeapon "rhs_weap_ak74m_gp25";
this addPrimaryWeaponItem "rhs_acc_dtk";
this addWeapon "Laserdesignator_03";

comment "Add items";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "tf_fadak_3";
this linkItem "ItemGPS";
this linkItem "NVGoggles_INDEP";
